name: averroes_app

description: Aplikasi mobile edukatif Averroes.

publish_to: none

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2808.1
  averroes_core:
    path: ../packages/core
  averroes_network:
    path: ../packages/network
  averroes_shared_models:
    path: ../packages/shared_models
  url_launcher: ^6.3.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - .env
